baseURL = "https://ggcarvalho.dev/"
languageCode = "en-us"
title = "Gabriel Carvalho"
theme = "ggcarvalho"
sectionPagesMenu = "main"
googleAnalytics = "G-QYTGXQ2FT8"
pygmentsStyle = "monokai"

[markup]
  [markup.highlight]
    tabWidth = 8
    lineNos = false
    style = "pygments"
    # see https://gohugo.io/getting-started/configuration-markup/#configure-markup
    # see https://jdhao.github.io/2019/12/29/hugo_html_not_shown/
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark]
      [markup.goldmark.renderer]
        unsafe = true
